version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sample_application
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
    networks:
      - dbcleanup-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_application
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbcleanup-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dbcleanup-network

volumes:
  postgres-data:
  redis-data:

networks:
  dbcleanup-network:
    driver: bridge 